### ISSUE TITLE
gulp-scss-lint error

### ISSUE THREAD

**Issue by co0kie** [Ghosh/cssFilters#3]
![image](https://cloud.githubusercontent.com/assets/906896/18617213/065f8b42-7dfd-11e6-9da8-621cf3327c5c.png)

**Comment by ghosh** [comment]
`scss-lint` has a hard dependency on the `scss_lint` ruby gem. You need to install that on your machine for it to work.

```
gem install scss_lint
```

That should do it. You can refer to the scss-lint docs for more info.

**Comment by co0kie** [comment]
Cool! it works! i have another one while clicking on the presets.

![image](https://cloud.githubusercontent.com/assets/906896/18620562/9cc147b6-7e47-11e6-935c-7d91f0c71dca.png)
