### ISSUE TITLE
Really nice work except for the errors

### ISSUE THREAD

**Issue by NJseo** [Ghosh/cssFilters#5]
I visited your site with Firefox and the preset filters worked great but the customizer on the right failed to work. I imagine because of all the Type(e) errors. There also seemed to be an issue with javascript compiling.

**Comment by ghosh** [comment]
Thanks for reporting this. Fixed in e7ffc9bb94f2fb7bc7a1ec1f224077e178fb366c.

**Comment by NJseo** [comment]
Thank you so much for the fix. I will test today!
